### ISSUE TITLE
Why are you public this repository ?

### ISSUE THREAD

**Issue by lequangnamsoraly2009** [trinhvanminh/advanced-RAG#5]
Why are you public this repository ?

**Comment by trinhvanminh** [comment]
I forgot to set it to private, but I'll make it public later today.

**Comment by lequangnamsoraly2009** [comment]
Dữ dằn z bro

**Comment by trinhvanminh** [comment]
Mở public ra nhưng quên set private lại bro. Tính làm ok rồi public sau

**Comment by lequangnamsoraly2009** [comment]
âu kê ~ Dùng để làm gì ?

**Comment by trinhvanminh** [comment]
Bot trả lời về document, về data cụ thể. 
- Document: bot trả lời về document của công ty, trả lời về tờ hướng dẫn sử dụng hay gì đó
- Data: bot có khả năng query để lấy dữ liệu (dạng dữ liệu có cấu trúc) như csv
